#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html

sudo sed -i "/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
# Restart the Nginx web server to put the changes into effect
sudo service nginx restart