#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy # Changed '>>' to 'sudo tee -a', shellcheck error
sudo echo "
frontend myfrontend
        bind 0.0.0.0:80
        default_backend myservers
backend myservers
        balance roundrobin
        server 3901-web-01 54.174.227.184:80 check
        server 3901-web-02 35.172.201.200:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg # Changed '>>' to 'sudo tee -a', shellcheck error

service haproxy restart