#!/usr/bin/env bash
# This is a script that displays: To infinity and beyond indefinitely
# With a sleep 2 in between each iteration I am invincible!!!
trap 'echo "I am invincible!!!"' SIGTERM
i=0
while [ $i ]; do
	echo 'To infinity and beyond'
	sleep 2
done