#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
n=1
while [ $n -le 8 ];
do
printf "Best School\n"
if [ $n -eq 3 ]
then
echo "bad luck"
elif [ $n -eq 6 ]
then
echo "good luck"
fi
((n++))
done